### ISSUE TITLE
Dependencies with exact versions

### ISSUE THREAD

**Issue by radubrehar** [mattdesl/dom-css#10]
Would you mind a PR that makes the dependencies have exact versions?
It's safer to depend on exact versions, although not 100% bullet-proof.

**Comment by mattdesl** [comment]
Pushed as 2.0.1. I usually don't lock down deps because it introduces other issues when maintaining hundreds of modules, and also because half the modules I depend on are my own. :smile:

But in this case dom-css and its dependencies are very stable/frozen and any further changes could be potentially dangerous, so I agree it makes sense to lock.

**Comment by radubrehar** [comment]
Thanks! That makes sense!
I also have a bunch of modules I own that I depend on, but just recently, a bug I introduced in one of my modules just affected other modules, so unless we write "bug-free" code, it does make sense to depend on exact versions. Thanks for considering!
